wandb_version: 1

epochs:
  desc: null
  value: 5
batch_size:
  desc: null
  value: 16
learning_rate:
  desc: null
  value: 1.0e-05
step_size:
  desc: null
  value: 30
gamma:
  desc: null
  value: 0.1
embedder_name:
  desc: null
  value: roberta-base
focal_alpha:
  desc: null
  value: 1.0
focal_gamma:
  desc: null
  value: 2.0
strategy:
  desc: null
  value: higher_level_activations
mode:
  desc: null
  value: classification
_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.15.2
    framework: huggingface
    huggingface_version: 4.29.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1684282951.460485
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.11.2
      5: 0.15.2
      6: 4.29.1
      8:
      - 5
